#!/bin/bash
set -e

# AgenDAV Modern Docker Entrypoint
# Generates settings.php from environment variables and runs migrations

CONFIG_FILE="/var/www/html/web/config/settings.php"
APACHE_CONF="/etc/apache2/conf-available/servername.conf"

# Configure Apache ServerName if provided
if [ -n "$AGENDAV_SERVER_NAME" ]; then
    echo "ServerName ${AGENDAV_SERVER_NAME}" > "$APACHE_CONF"
    a2enconf servername > /dev/null 2>&1 || true
    echo "Apache ServerName set to: ${AGENDAV_SERVER_NAME}"
else
    # Suppress Apache warning about missing ServerName
    echo "ServerName localhost" > "$APACHE_CONF"
    a2enconf servername > /dev/null 2>&1 || true
fi

# Generate encryption key and CSRF secret if not provided
if [ -z "$AGENDAV_ENCRYPTION_KEY" ]; then
    AGENDAV_ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)
    echo "WARNING: AGENDAV_ENCRYPTION_KEY not set, using randomly generated key."
    echo "         This will invalidate stored passwords on container restart!"
fi

if [ -z "$AGENDAV_CSRF_SECRET" ]; then
    AGENDAV_CSRF_SECRET=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)
    echo "WARNING: AGENDAV_CSRF_SECRET not set, using randomly generated secret."
fi

# Convert boolean string to PHP boolean
php_bool() {
    case "${1,,}" in
        true|1|yes) echo "true" ;;
        *) echo "false" ;;
    esac
}

# Generate settings.php
cat > "$CONFIG_FILE" << EOPHP
<?php
/**
 * AgenDAV Settings
 * Auto-generated by Docker entrypoint - do not edit manually
 */

// Site title
\$app['site.title'] = '${AGENDAV_SITE_TITLE:-AgenDAV}';

// Site logo (should be placed in public/img). Optional
\$app['site.logo'] = '${AGENDAV_SITE_LOGO:-agendav_100transp.png}';

// Site footer. Optional
\$app['site.footer'] = '${AGENDAV_SITE_FOOTER:-AgenDAV Modern}';

// Trusted proxy IPs (comma-separated)
\$app['proxies'] = array_filter(explode(',', '${AGENDAV_PROXIES:-}'));

// Database settings
\$app['db.options'] = [
    'dbname' => '${AGENDAV_DB_NAME:-agendav}',
    'user' => '${AGENDAV_DB_USER:-agendav}',
    'password' => '${AGENDAV_DB_PASSWORD}',
    'host' => '${AGENDAV_DB_HOST:-localhost}',
    'port' => ${AGENDAV_DB_PORT:-3306},
    'driver' => '${AGENDAV_DB_DRIVER:-pdo_mysql}'
];

// Encryption key (IMPORTANT: keep this secret and consistent)
\$app['encryption.key'] = '${AGENDAV_ENCRYPTION_KEY}';

// CSRF secret
\$app['csrf.secret'] = '${AGENDAV_CSRF_SECRET}';

// Log path
\$app['log.path'] = '${AGENDAV_LOG_PATH:-/var/www/html/web/var/log/}';

// Log level
\$app['log.level'] = '${AGENDAV_LOG_LEVEL:-INFO}';

// CalDAV base URL
\$app['caldav.baseurl'] = '${AGENDAV_CALDAV_BASEURL}';

// Authentication method required by CalDAV server (basic or digest)
\$app['caldav.authmethod'] = '${AGENDAV_CALDAV_AUTHMETHOD:-basic}';

// Whether to show public CalDAV URLs
\$app['caldav.publicurls'] = $(php_bool "${AGENDAV_CALDAV_PUBLIC_URLS:-true}");

// Public CalDAV base URL (shown to users)
\$app['caldav.baseurl.public'] = '${AGENDAV_CALDAV_BASEURL_PUBLIC:-}';

// CalDAV connection timeout (0 = wait forever)
\$app['caldav.connect.timeout'] = ${AGENDAV_CALDAV_CONNECT_TIMEOUT:-0};

// CalDAV response timeout (0 = wait forever)
\$app['caldav.response.timeout'] = ${AGENDAV_CALDAV_RESPONSE_TIMEOUT:-0};

// Whether to verify SSL certificates
\$app['caldav.certificate.verify'] = $(php_bool "${AGENDAV_CALDAV_VERIFY_CERT:-true}");

// Calendar sharing
\$app['calendar.sharing'] = $(php_bool "${AGENDAV_CALENDAR_SHARING:-false}");

// Default timezone
\$app['defaults.timezone'] = '${AGENDAV_TIMEZONE:-UTC}';

// Default language
\$app['defaults.language'] = '${AGENDAV_LANGUAGE:-en}';

// Default time format (12 or 24)
\$app['defaults.time_format'] = '${AGENDAV_TIME_FORMAT:-24}';

// Default date format (ymd, dmy, mdy)
\$app['defaults.date_format'] = '${AGENDAV_DATE_FORMAT:-ymd}';

// Default first day of week (0 = Sunday, 1 = Monday)
\$app['defaults.weekstart'] = ${AGENDAV_WEEKSTART:-1};

// Show week numbers
\$app['defaults.show_week_nb'] = $(php_bool "${AGENDAV_SHOW_WEEK_NB:-false}");

// Show "now" indicator
\$app['defaults.show_now_indicator'] = $(php_bool "${AGENDAV_SHOW_NOW_INDICATOR:-true}");

// Default number of days in list view (7, 14, or 31)
\$app['defaults.list_days'] = ${AGENDAV_LIST_DAYS:-7};

// Default view (month, week, day, or list)
\$app['defaults.default_view'] = '${AGENDAV_DEFAULT_VIEW:-month}';

// Logout redirection URL (optional)
\$app['logout.redirection'] = '${AGENDAV_LOGOUT_REDIRECT:-}';

// Twig cache directory
\$app['twig.options'] = ['cache' => '/var/cache/twig'];

// Session settings
\$app['session.storage.options'] = [
    'name' => 'agendav_sess',
    'cookie_lifetime' => ${AGENDAV_SESSION_LIFETIME:-0},
    'gc_probability' => 1,
    'gc_divisor' => 10,
    'gc_maxlifetime' => ${AGENDAV_SESSION_MAXLIFETIME:-1200},
    'lifetime' => ${AGENDAV_SESSION_MAXLIFETIME:-1200},
    'cookie_httponly' => true,
];
EOPHP

echo "Configuration generated at $CONFIG_FILE"

# Run database migrations if requested
if [ "${AGENDAV_RUN_MIGRATIONS:-false}" = "true" ]; then
    echo "Running database migrations..."
    cd /var/www/html
    php agendavcli migrations:migrate --no-interaction || {
        echo "WARNING: Database migrations failed. Database may not be ready yet."
    }
fi

# Execute the main command
exec "$@"
